# App name
spring.application.name=kakebo

# Port
server.port=9090

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

## Debugging comment or un coment leve
logging.level.root=ERROR
# logging.level.root=DEBUG

## Database configuration useful for testing
spring.datasource.url=jdbc:postgresql://localhost:52010/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

## This property set to create will be create the database tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

## Flyway Config
spring.flyway.enabled=false
# spring.flyway.locations=classpath:db/migration

## Docker Compose - Disabled for development
spring.docker.compose.enabled=false
