INSERT INTO T_EXPENSES (ID, AMOUNT, EXPENSE_NAME, EXPENSE_DATE)
values (1, 10, 'gasto1', current_date);
INSERT INTO T_EXPENSES (ID, AMOUNT, EXPENSE_NAME, EXPENSE_DATE)
values (2, 20, 'gasto2', current_date);